spec:
  inputs:
    language:
      description: "Program Language for Scan and Quality Gate"
      type: string
      default: "node"
      options:
      - maven # Maven
      - gradle # Gradle
      - dotnet # C#/.NET
      - python # Python
      - node # Node.js
      - go # Go
      - other # Other
    arch:
      description: "Architecture for Scan and Quality Gate"
      type: string
      default: "arm64"
      options:
      - arm64 # ARM64
      - amd64 # AMD64
    excludes:
      description: "Files and folders to exclude from analysis"
      type: string
      default: ""
    stage:
      description: "Stage to run SonarQube"
      type: string
      default: sast
    environment:
      description: "Environment for Scan and Quality Gate"
      type: string
      default: sonarqube
    image:
      description: "Docker image to use for the job"
      type: string
      default: "public.ecr.aws/n6a9k4a7/deploy:1-sonarqube"
    # Sonarqube Quality Gate variables
    quality_gate:
      description: "Wait for Quality Gate"
      type: boolean
      default: true
    quality_gate_timeout:
      description: "Timeout for Quality Gate"
      type: string
      default: "300"
    #.NET variables
    dotnet_version:
      description: ".NET version"
      type: string
      default: "10.0"
    dotnet_path_sln_or_csproj:
      description: "Path for .sln or .csproj"
      type: string
      default: ""
    dotnet_test_and_coverage:
      description: "Run tests and collect coverage for .NET projects"
      type: boolean
      default: false
    # Gradle variables
    gradle_version:
      description: "Gradle version"
      type: string
      default: "9-jdk17-jammy"
    # Maven variables
    maven_version:
      description: "Maven version"
      type: string
      default: "3.9"
    go_version:
      description: "Go version"
      type: string
      default: "1.26"
---
default:
  retry:
    max: 2
    when:
    - runner_system_failure
    - stuck_or_timeout_failure
    - unknown_failure
    - api_failure
    - job_execution_timeout

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

stages:
- $[[ inputs.stage ]]

# ARM64
sonarqube:
  rules:
  - if: '"$[[ inputs.language | expand_vars ]]" == "" || "$[[ inputs.language | expand_vars ]]" == "node" || "$[[ inputs.language | expand_vars ]]" == "other" && "$[[ inputs.arch | expand_vars ]]" == "arm64"'
  environment: $[[ inputs.environment ]]
  stage: $[[ inputs.stage ]]
  image: $[[ inputs.image | expand_vars ]]
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
    - "${SONAR_USER_HOME}/cache"
    - sonar-scanner/
  before_script:
  # Verifica se as variáveis obrigatórias estão definidas
  - '[ -n "${SONAR_HOST_URL:-}" ] || { echo "ERROR: SONAR_HOST_URL is not defined"; exit 1; }'
  - '[ -n "${SONAR_TOKEN:-}" ]    || { echo "ERROR: SONAR_TOKEN is not defined"; exit 1; }'
  script:
  - sonar-scanner -Dsonar.host.url="$SONAR_HOST_URL" -Dsonar.token="$SONAR_TOKEN" -Dsonar.projectKey="$SONAR_PROJECT_KEY" -Dsonar.sourceEncoding=UTF-8 -Dsonar.exclusions="$[[ inputs.excludes | expand_vars ]]"
  - |
    exit_status=$?
    if [ $exit_status -eq 0 ]; then
      echo "SonarQube successfully!"
      echo "Url to project: $SONAR_HOST_URL/dashboard?id=$SONAR_PROJECT_KEY"
    else
      echo "SonarQube failed!"
      echo "Url to project: $SONAR_HOST_URL/dashboard?id=$SONAR_PROJECT_KEY"
      exit 1
    fi

# AMD64
sonarqube_amd64:
  rules:
  - if: '"$[[ inputs.language | expand_vars ]]" == "" || "$[[ inputs.language | expand_vars ]]" == "node" || "$[[ inputs.language | expand_vars ]]" == "other" && "$[[ inputs.arch | expand_vars ]]" == "amd64"'
  environment: $[[ inputs.environment ]]
  stage: $[[ inputs.stage ]]
  image:
    name: sonarsource/sonar-scanner-cli:11
    entrypoint: [ "" ]
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
    - "${SONAR_USER_HOME}/cache"
    - sonar-scanner/
  before_script:
  # Verifica se as variáveis obrigatórias estão definidas
  - '[ -n "${SONAR_HOST_URL:-}" ] || { echo "ERROR: SONAR_HOST_URL is not defined"; exit 1; }'
  - '[ -n "${SONAR_TOKEN:-}" ]    || { echo "ERROR: SONAR_TOKEN is not defined"; exit 1; }'
  script:
  - sonar-scanner -Dsonar.host.url="$SONAR_HOST_URL" -Dsonar.token="$SONAR_TOKEN" -Dsonar.projectKey="$SONAR_PROJECT_KEY" -Dsonar.sourceEncoding=UTF-8 -Dsonar.exclusions="$[[ inputs.excludes | expand_vars ]]"
  - |
    exit_status=$?
    if [ $exit_status -eq 0 ]; then
      echo "SonarQube scan completed successfully."
      echo "Url to project: $SONAR_HOST_URL/dashboard?id=$SONAR_PROJECT_KEY"
    else
      echo "SonarQube scan failed."
      echo "Url to project: $SONAR_HOST_URL/dashboard?id=$SONAR_PROJECT_KEY"
      exit 1
    fi
  tags:
  - amd64-dedicated

# Python
sonar_python:
  rules:
  - if: '"$[[ inputs.language | expand_vars ]]" == "python"'
  environment: $[[ inputs.environment ]]
  stage: $[[ inputs.stage ]]
  image:
    name: $[[ inputs.image | expand_vars ]]
    entrypoint: [ "" ]
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
    - "${SONAR_USER_HOME}/cache"
    - sonar-scanner/
  script:
  - >
    sonar-scanner -Dsonar.host.url="$SONAR_HOST_URL" -Dsonar.token="$SONAR_TOKEN" -Dsonar.projectKey="$SONAR_PROJECT_KEY" -Dsonar.sourceEncoding=UTF-8 -Dsonar.qualitygate.wait=$[[ inputs.quality_gate ]] -Dsonar.qualitygate.timeout=$[[ inputs.quality_gate_timeout ]]

#.NET
sonar_dotnet_test_coverage:
  rules:
  - if: '"$[[ inputs.language | expand_vars ]]" == "dotnet" && "$[[ inputs.dotnet_test_and_coverage ]]" == "true"'
  image: mcr.microsoft.com/dotnet/sdk:$[[inputs.dotnet_version | expand_vars]]-alpine
  stage: $[[ inputs.stage ]]
  environment: $[[ inputs.environment ]]
  before_script:
  - apk add --no-cache bash curl jq
  - dotnet tool install --global dotnet-sonarscanner
  - export PATH="$HOME/.dotnet/tools:$PATH"
  # Verifica se as variáveis obrigatórias estão definidas
  - '[ -n "${SONAR_HOST_URL:-}" ] || { echo "ERROR: SONAR_HOST_URL is not defined"; exit 1; }'
  - '[ -n "${SONAR_TOKEN:-}" ]    || { echo "ERROR: SONAR_TOKEN is not defined"; exit 1; }'

  script:
  # 1) Inicia a análise (apontando para OpenCover)
  - >
    dotnet-sonarscanner begin /k:"$SONAR_PROJECT_KEY" /d:sonar.host.url="$SONAR_HOST_URL" /d:sonar.token="$SONAR_TOKEN" /d:sonar.cs.opencover.reportsPaths="TestResults/**/coverage.opencover.xml" /d:sonar.cs.vstest.reportsPaths="TestResults/*.trx"

  # 2) Build da solução/projeto (utilizando --no-incremental para garantir que tudo seja recompilado)
  - >
    dotnet build $[[inputs.dotnet_path_sln_or_csproj]] --no-incremental

  # 3) Testes + cobertura (GERA DOIS FORMATOS: cobertura + opencover)
  - >
    dotnet test --configuration Debug --results-directory TestResults --collect:"XPlat Code Coverage;Format=cobertura,opencover"

  # 4) Consolida 1 arquivo Cobertura com nome estável para o GitLab
  - >
    COB_FILE=$(find TestResults -name 'coverage.cobertura.xml' | head -n 1) && cp "$COB_FILE" coverage.cobertura.xml

  # 5) Finaliza a análise e aguarda o Quality Gate (timeout de 5 minutos)
  - >
    dotnet-sonarscanner end /d:sonar.token="$SONAR_TOKEN" /d:sonar.qualitygate.wait=$[[ inputs.quality_gate ]] /d:sonar.qualitygate.timeout=$[[ inputs.quality_gate_timeout ]]

  artifacts:
    when: always
    paths:
    - TestResults/**
    - coverage.cobertura.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.cobertura.xml

sonar_dotnet:
  rules:
  - if: '"$[[ inputs.language | expand_vars ]]" == "dotnet"'
  environment: $[[ inputs.environment ]]
  stage: $[[ inputs.stage ]]
  image: $IMAGE_DOTNET
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
    - "${SONAR_USER_HOME}/cache"
    - sonar-scanner/
  script:
  - "dotnet tool install --global dotnet-sonarscanner"
  - 'export PATH="$PATH:$HOME/.dotnet/tools"'
  - 'dotnet sonarscanner begin /d:sonar.token="$SONAR_TOKEN" /d:"sonar.host.url=$SONAR_HOST_URL" '
  - "dotnet build"
  - 'dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"'

# Maven
sonar_maven:
  rules:
  - if: '"$[[ inputs.language | expand_vars ]]" == "maven"'
  environment: $[[ inputs.environment ]]
  stage: $[[ inputs.stage ]]
  image: "maven:$[[inputs.maven_version | expand_vars]]"
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
    - "${SONAR_USER_HOME}/cache"
    - sonar-scanner/
  before_script:
  # Verifica se as variáveis obrigatórias estão definidas
  - '[ -n "${SONAR_HOST_URL:-}" ] || { echo "ERROR: SONAR_HOST_URL is not defined"; exit 1; }'
  - '[ -n "${SONAR_TOKEN:-}" ]    || { echo "ERROR: SONAR_TOKEN is not defined"; exit 1; }'
  script:
  - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.host.url="$SONAR_HOST_URL" -Dsonar.token="$SONAR_TOKEN" -Dsonar.projectKey="$SONAR_PROJECT_KEY" -Dsonar.sourceEncoding=UTF-8 -Dsonar.exclusions="$[[ inputs.excludes | expand_vars ]]"

# Gradle
sonar_gradle:
  rules:
  - if: '"$[[ inputs.language | expand_vars ]]" == "gradle"'
  environment: $[[ inputs.environment ]]
  stage: $[[ inputs.stage ]]
  image: "gradle:$[[inputs.gradle_version | expand_vars]]"
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
    - "${SONAR_USER_HOME}/cache"
    - sonar-scanner/
  before_script:
  # Verifica se as variáveis obrigatórias estão definidas
  - '[ -n "${SONAR_HOST_URL:-}" ] || { echo "ERROR: SONAR_HOST_URL is not defined"; exit 1; }'
  - '[ -n "${SONAR_TOKEN:-}" ]    || { echo "ERROR: SONAR_TOKEN is not defined"; exit 1; }'
  script: gradle sonarqube -Dsonar.host.url="$SONAR_HOST_URL" -Dsonar.token="$SONAR_TOKEN" -Dsonar.projectKey="$SONAR_PROJECT_KEY" -Dsonar.sourceEncoding=UTF-8 -Dsonar.exclusions="$[[ inputs.excludes | expand_vars ]]"

# Go
sonar_go:
  rules:
  - if: '"$[[ inputs.language | expand_vars ]]" == "go"'
  environment: $[[ inputs.environment ]]
  stage: $[[ inputs.stage ]]
  image: "golang:$[[inputs.go_version | expand_vars]]-alpine"
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
    - "${SONAR_USER_HOME}/cache"
    - sonar-scanner/
  before_script:
  # Verifica se as variáveis obrigatórias estão definidas
  - '[ -n "${SONAR_HOST_URL:-}" ] || { echo "ERROR: SONAR_HOST_URL is not defined"; exit 1; }'
  - '[ -n "${SONAR_TOKEN:-}" ]    || { echo "ERROR: SONAR_TOKEN is not defined"; exit 1; }'
  - apk add --no-cache bash curl unzip
  - curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip && unzip sonar-scanner.zip -d /opt && rm sonar-scanner.zip
  - export PATH="/opt/sonar-scanner-4.8.0.2856-linux/bin:$PATH" && sonar-scanner --version
  script:
  - sonar-scanner -Dsonar.host.url="$SONAR_HOST_URL" -Dsonar.token="$SONAR_TOKEN" -Dsonar.projectKey="$SONAR_PROJECT_KEY" -Dsonar.sourceEncoding=UTF-8 -Dsonar.exclusions="$[[ inputs.excludes | expand_vars ]]"
